const os = require('os');
const path = require('path');

/**
 * Generates security safety configurations for Claude Code 2.0
 * Detects common security vulnerabilities in generated code
 */

/**
 * Main generator function
 */
function generateSecuritySafety(analysis, options = {}) {
  return {
    hooks: generateSecurityHooks(),
    permissions: generateSecurityPermissions(),
    claudeMdSection: generateSecurityProtocol()
  };
}

/**
 * Generate PreToolUse hooks for security validation
 */
function generateSecurityHooks() {
  const homeDir = os.homedir();
  const hookPath = path.join(homeDir, '.claude', 'hooks', 'security-check.sh');

  return {
    "PostToolUse": [{
      "matcher": "Edit|Write",
      "hooks": [{
        "type": "command",
        "command": `"${hookPath}" "$CLAUDE_FILE_PATHS"`,
        "timeout": 10,
        "continueOnError": true  // Warn but don't block (false positives possible)
      }]
    }]
  };
}

/**
 * Generate security-related permissions
 */
function generateSecurityPermissions() {
  const homeDir = os.homedir();
  const hookPath = path.join(homeDir, '.claude', 'hooks', 'security-check.sh');

  return {
    allow: [
      // Security hook needs to run without prompts
      `Bash("${hookPath}":*)`
    ],
    deny: [
      // Prevent direct execution of dangerous commands
      "Bash(eval:*)",
      "Bash(exec:*)"
    ]
  };
}

/**
 * Generate CLAUDE.md security protocol section
 */
function generateSecurityProtocol() {
  return `
## SECURITY PROTOCOL (MANDATORY)

Before writing ANY code that handles:
- User input
- Database queries
- External API calls
- File system operations
- Authentication/authorization

### Input Validation Checklist
- [ ] All user input is validated and sanitized
- [ ] Input length limits are enforced
- [ ] Type checking is performed
- [ ] Whitelist validation for known values

### SQL Safety (if using SQL)
- [ ] Use parameterized queries ALWAYS
- [ ] NEVER concatenate user input into SQL strings
- [ ] Use ORM query builders when possible
- [ ] Validate all query parameters

### Code Execution Safety
- [ ] NEVER use \`eval()\` or \`exec()\` with user input
- [ ] Avoid dynamic code execution when possible
- [ ] If dynamic execution needed, use safe alternatives (Function constructor with strict validation)

### Credential Safety
- [ ] NO hardcoded passwords, API keys, or secrets
- [ ] Use environment variables (\`.env\` files)
- [ ] Never commit credentials to git
- [ ] Use secret management tools in production

### XSS Prevention
- [ ] Escape all user-generated content before rendering
- [ ] Use framework-provided escaping (React JSX auto-escapes)
- [ ] Set Content-Security-Policy headers
- [ ] Validate and sanitize HTML input

### Common Vulnerabilities to Avoid
❌ **SQL Injection**: \`"SELECT * FROM users WHERE id = " + userId\`
✅ **Safe**: \`db.query("SELECT * FROM users WHERE id = ?", [userId])\`

❌ **eval() usage**: \`eval(userInput)\`
✅ **Safe**: Use JSON.parse for data, proper parsers for code

❌ **Hardcoded secrets**: \`const API_KEY = "sk-1234567890"\`
✅ **Safe**: \`const API_KEY = process.env.API_KEY\`

❌ **Command injection**: \`exec("git commit -m " + userMessage)\`
✅ **Safe**: Use libraries with proper escaping or parameterized commands
`;
}

/**
 * Security check hook script template
 */
const SECURITY_CHECK_HOOK_TEMPLATE = `#!/bin/bash
# Security Check Hook
# Generated by ccxl v2.0.0
# Scans code for common security vulnerabilities

FILES="$1"

# Color codes
RED='\\033[0;31m'
YELLOW='\\033[1;33m'
NC='\\033[0m' # No Color

WARNINGS=0

# Check each modified file
for file in $FILES; do
    if [ ! -f "$file" ]; then
        continue
    fi

    # Only check code files
    case "$file" in
        *.js|*.ts|*.jsx|*.tsx|*.py|*.go|*.rb|*.php)
            ;;
        *)
            continue
            ;;
    esac

    echo "🔍 Scanning: $file"

    # Check for SQL injection patterns
    if grep -nE "(SELECT|INSERT|UPDATE|DELETE|FROM|WHERE).*\\+.*\\$|\\+.*\\(|exec\\(.*SELECT" "$file" 2>/dev/null; then
        echo -e "\${YELLOW}⚠️  Possible SQL injection in $file\${NC}"
        echo "   Use parameterized queries instead of string concatenation"
        WARNINGS=$((WARNINGS + 1))
    fi

    # Check for eval() usage
    if grep -nE "\\beval\\s*\\(|\\bexec\\s*\\(" "$file" 2>/dev/null; then
        echo -e "\${YELLOW}⚠️  eval()/exec() detected in $file\${NC}"
        echo "   Avoid dynamic code execution, especially with user input"
        WARNINGS=$((WARNINGS + 1))
    fi

    # Check for hardcoded credentials
    if grep -niE "(password|api[_-]?key|secret|token|auth)\\s*=\\s*['\\\"].{8,}" "$file" 2>/dev/null; then
        echo -e "\${RED}🚫 Possible hardcoded credentials in $file\${NC}"
        echo "   Use environment variables instead"
        WARNINGS=$((WARNINGS + 1))
    fi

    # Check for command injection
    if grep -nE "exec\\(.*\\+|system\\(.*\\+|spawn\\(.*\\+" "$file" 2>/dev/null; then
        echo -e "\${YELLOW}⚠️  Possible command injection in $file\${NC}"
        echo "   Use parameterized command execution"
        WARNINGS=$((WARNINGS + 1))
    fi

    # Check for innerHTML/dangerouslySetInnerHTML (XSS risk)
    if grep -nE "innerHTML\\s*=|dangerouslySetInnerHTML" "$file" 2>/dev/null; then
        echo -e "\${YELLOW}⚠️  XSS risk detected in $file\${NC}"
        echo "   Use framework-provided safe rendering methods"
        WARNINGS=$((WARNINGS + 1))
    fi
done

if [ "$WARNINGS" -gt 0 ]; then
    echo ""
    echo -e "\${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\${NC}"
    echo -e "\${YELLOW}⚠️  $WARNINGS security warning(s) found\${NC}"
    echo ""
    echo "Review the warnings above and fix if needed."
    echo "These are automated checks and may have false positives."
fi

# Always succeed (warnings only, not blocking)
exit 0
`;

module.exports = {
  generateSecuritySafety,
  generateSecurityHooks,
  generateSecurityPermissions,
  generateSecurityProtocol,
  SECURITY_CHECK_HOOK_TEMPLATE
};
